services:
  app:
    image: node:latest
    tty: true
    environment:
      TZ: Asia/Tokyo
      LANG: en_US.UTF-8
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: yarn start
